name: Quality checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        # https://github.com/oven-sh/setup-bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Security audit
        run: bun audit

      - name: Build project
        working-directory: pimdb
        run: bun run build
